export interface Agent {
  id: number;
  name: string;
  role: string;
  specialty: string;
  specialties: string[];
  deals: number;
  exp: number;
  rating: number;
  img: string;
  category: string;
  city: string;
  phone: string;
  email: string;
  bio: string;
  languages: string[];
  activeListings: number;
  soldListings: number;
  responseTime: string;
  reviews: { name: string; text: string; rating: number; date: string }[];
}

const agents: Agent[] = [
  {
    id: 0,
    name: "Ahmed Raza",
    role: "Senior Property Agent",
    specialty: "Luxury",
    specialties: ["Luxury Villas", "Residential", "Investment"],
    deals: 48,
    exp: 12,
    rating: 4.9,
    img: "https://images.unsplash.com/photo-1560250097-0b93528c311a?w=500&q=80",
    category: "Luxury",
    city: "Lahore",
    phone: "+92 300 1234567",
    email: "ahmed.raza@luxestate.pk",
    bio: "Ahmed is a seasoned luxury property specialist with over 12 years of experience in Lahore's premium real estate market. He has helped hundreds of clients find their dream homes in DHA, Gulberg, and Bahria Town. Known for his deep market knowledge and client-first approach.",
    languages: ["Urdu", "English", "Punjabi"],
    activeListings: 8,
    soldListings: 48,
    responseTime: "< 1 hour",
    reviews: [
      { name: "Bilal Ahmed", text: "Ahmed helped us find our dream villa in DHA. Extremely professional and knowledgeable.", rating: 5, date: "Nov 2024" },
      { name: "Sana Malik", text: "Best agent in Lahore. Closed our deal in record time with great terms.", rating: 5, date: "Oct 2024" },
      { name: "Tariq Hassan", text: "Very responsive and honest. Highly recommend for luxury properties.", rating: 5, date: "Sep 2024" },
    ],
  },
  {
    id: 1,
    name: "Sara Khan",
    role: "Residential Specialist",
    specialty: "Residential",
    specialties: ["Residential", "Apartments", "Plots"],
    deals: 31,
    exp: 7,
    rating: 4.8,
    img: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=500&q=80",
    category: "Residential",
    city: "Karachi",
    phone: "+92 321 9876543",
    email: "sara.khan@luxestate.pk",
    bio: "Sara specialises in residential properties across Karachi's most sought-after neighbourhoods including Clifton, DHA, and Bahria Town. With 7 years of experience, she brings a warm, client-focused approach to every transaction.",
    languages: ["Urdu", "English"],
    activeListings: 6,
    soldListings: 31,
    responseTime: "< 2 hours",
    reviews: [
      { name: "Kamran Ali", text: "Sara was incredibly helpful throughout our apartment search in Clifton.", rating: 5, date: "Dec 2024" },
      { name: "Nadia Hussain", text: "Very professional and patient. Found us exactly what we were looking for.", rating: 5, date: "Nov 2024" },
      { name: "Asad Mirza", text: "Great experience. Sara knows Karachi's market inside out.", rating: 4, date: "Oct 2024" },
    ],
  },
  {
    id: 2,
    name: "Usman Ali",
    role: "Commercial & Investment Advisor",
    specialty: "Commercial",
    specialties: ["Commercial", "Investment", "Plots"],
    deals: 24,
    exp: 9,
    rating: 4.9,
    img: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=500&q=80",
    category: "Commercial",
    city: "Islamabad",
    phone: "+92 333 4567890",
    email: "usman.ali@luxestate.pk",
    bio: "Usman is Islamabad's go-to commercial real estate advisor with expertise in Blue Area, F-sectors, and G-sectors. He has facilitated major commercial transactions for corporate clients and investors, delivering consistent returns.",
    languages: ["Urdu", "English"],
    activeListings: 5,
    soldListings: 24,
    responseTime: "< 3 hours",
    reviews: [
      { name: "Zubair Sheikh", text: "Usman helped us secure a prime commercial space in Blue Area. Excellent negotiator.", rating: 5, date: "Dec 2024" },
      { name: "Hina Baig", text: "Very knowledgeable about Islamabad's commercial market. Highly recommended.", rating: 5, date: "Nov 2024" },
      { name: "Faisal Qureshi", text: "Professional and efficient. Closed our deal smoothly.", rating: 4, date: "Oct 2024" },
    ],
  },
  {
    id: 3,
    name: "Fatima Malik",
    role: "Luxury Estate Consultant",
    specialty: "Luxury",
    specialties: ["Luxury Villas", "Luxury Apartments", "Commercial"],
    deals: 56,
    exp: 15,
    rating: 5.0,
    img: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=500&q=80",
    category: "Luxury",
    city: "Lahore",
    phone: "+92 345 6789012",
    email: "fatima.malik@luxestate.pk",
    bio: "With 15 years in luxury real estate, Fatima is one of Pakistan's most decorated property consultants. She has handled some of the most prestigious transactions in Lahore and Islamabad, with a portfolio exceeding PKR 2 billion in total sales.",
    languages: ["Urdu", "English", "French"],
    activeListings: 11,
    soldListings: 56,
    responseTime: "< 1 hour",
    reviews: [
      { name: "Imran Chaudhry", text: "Fatima is simply the best. She found us a stunning villa in Gulberg within a week.", rating: 5, date: "Dec 2024" },
      { name: "Rabia Siddiqui", text: "Exceptional service. Fatima's market knowledge is unmatched.", rating: 5, date: "Nov 2024" },
      { name: "Omar Farooq", text: "Highly professional. Made the entire process stress-free.", rating: 5, date: "Oct 2024" },
    ],
  },
  {
    id: 4,
    name: "Bilal Hussain",
    role: "Residential & Rental Agent",
    specialty: "Residential",
    specialties: ["Residential", "Rentals", "Apartments"],
    deals: 19,
    exp: 4,
    rating: 4.7,
    img: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=500&q=80",
    category: "Residential",
    city: "Karachi",
    phone: "+92 312 3456789",
    email: "bilal.hussain@luxestate.pk",
    bio: "Bilal is a rising star in Karachi's residential market, specialising in apartments and rental properties. His energy, dedication, and deep understanding of client needs have earned him a loyal client base in just 4 years.",
    languages: ["Urdu", "English"],
    activeListings: 4,
    soldListings: 19,
    responseTime: "< 2 hours",
    reviews: [
      { name: "Ayesha Noor", text: "Bilal was very helpful in finding us a rental apartment in Clifton.", rating: 5, date: "Nov 2024" },
      { name: "Saad Rehman", text: "Quick, responsive, and honest. Great experience overall.", rating: 4, date: "Oct 2024" },
      { name: "Maryam Iqbal", text: "Very professional for his experience level. Will use again.", rating: 5, date: "Sep 2024" },
    ],
  },
  {
    id: 5,
    name: "Nadia Shah",
    role: "Commercial Broker",
    specialty: "Commercial",
    specialties: ["Commercial", "Residential", "Investment"],
    deals: 37,
    exp: 10,
    rating: 4.8,
    img: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=500&q=80",
    category: "Commercial",
    city: "Rawalpindi",
    phone: "+92 300 9876543",
    email: "nadia.shah@luxestate.pk",
    bio: "Nadia is a versatile broker with expertise spanning commercial and residential properties in Rawalpindi and Islamabad. Her analytical approach to investment properties has helped clients achieve exceptional returns.",
    languages: ["Urdu", "English"],
    activeListings: 7,
    soldListings: 37,
    responseTime: "< 2 hours",
    reviews: [
      { name: "Waqas Butt", text: "Nadia helped us find the perfect office space in Rawalpindi. Very professional.", rating: 5, date: "Dec 2024" },
      { name: "Sadia Akhtar", text: "Excellent knowledge of the twin cities market. Highly recommend.", rating: 5, date: "Nov 2024" },
      { name: "Rizwan Khan", text: "Great experience. Nadia is thorough and reliable.", rating: 4, date: "Oct 2024" },
    ],
  },
  {
    id: 6,
    name: "Tariq Mehmood",
    role: "Luxury Property Advisor",
    specialty: "Luxury",
    specialties: ["Luxury Villas", "Commercial", "Plots"],
    deals: 42,
    exp: 11,
    rating: 4.9,
    img: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=500&q=80",
    category: "Luxury",
    city: "Peshawar",
    phone: "+92 333 1122334",
    email: "tariq.mehmood@luxestate.pk",
    bio: "Tariq brings 11 years of luxury real estate expertise to Peshawar and KPK's growing property market. He has been instrumental in introducing premium developments to the region and has a strong network of high-net-worth clients.",
    languages: ["Urdu", "English", "Pashto"],
    activeListings: 9,
    soldListings: 42,
    responseTime: "< 1 hour",
    reviews: [
      { name: "Adnan Yousaf", text: "Tariq is the best agent in Peshawar. Found us a luxury villa quickly.", rating: 5, date: "Dec 2024" },
      { name: "Gulnaz Bibi", text: "Very professional and knowledgeable. Highly recommended.", rating: 5, date: "Nov 2024" },
      { name: "Shahid Afridi", text: "Excellent service. Tariq made the whole process easy.", rating: 5, date: "Oct 2024" },
    ],
  },
  {
    id: 7,
    name: "Zara Qureshi",
    role: "Residential & Plot Consultant",
    specialty: "Residential",
    specialties: ["Residential", "Plots", "Luxury Apartments"],
    deals: 28,
    exp: 6,
    rating: 4.8,
    img: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=500&q=80",
    category: "Residential",
    city: "Islamabad",
    phone: "+92 321 5544332",
    email: "zara.qureshi@luxestate.pk",
    bio: "Zara is a dedicated residential consultant based in Islamabad, with a focus on F and G sectors. Her attention to detail and commitment to client satisfaction have made her one of the most trusted agents in the capital.",
    languages: ["Urdu", "English"],
    activeListings: 5,
    soldListings: 28,
    responseTime: "< 2 hours",
    reviews: [
      { name: "Hamza Nawaz", text: "Zara helped us find a great plot in F-10. Very knowledgeable.", rating: 5, date: "Dec 2024" },
      { name: "Lubna Arif", text: "Professional and responsive. Made the buying process smooth.", rating: 4, date: "Nov 2024" },
      { name: "Umar Farhan", text: "Great experience with Zara. Will definitely work with her again.", rating: 5, date: "Oct 2024" },
    ],
  },
];

export default agents;
